@echo off
REM ============================================================
REM  clone-company.bat
REM  Duplicate this Landco app into a new company folder + DB + container.
REM
REM  Usage:  clone-company.bat
REM  You'll be prompted for:
REM    - Source folder (this app)
REM    - Destination folder (new company)
REM    - Company short name (used in DB name + container names, e.g. ebony)
REM    - Web port  (e.g. 8081)
REM    - API port  (e.g. 4001)
REM    - DB  port  (e.g. 5433)
REM ============================================================

setlocal enabledelayedexpansion

set /p SRC="Source folder (e.g. C:\Lovable\Landco): "
set /p DST="Destination folder (e.g. C:\Lovable\EbonyBeach): "
set /p NAME="Company short name (lowercase, no spaces, e.g. ebony): "
set /p WEBPORT="Web port (default 8081): "
set /p APIPORT="API port (default 4001): "
set /p DBPORT="DB port  (default 5433): "

if "%WEBPORT%"=="" set WEBPORT=8081
if "%APIPORT%"=="" set APIPORT=4001
if "%DBPORT%"=="" set DBPORT=5433

echo.
echo === Copying files (excluding node_modules, .git, dist) ===
robocopy "%SRC%" "%DST%" /E /XD node_modules .git dist .vite /XF *.log
if errorlevel 8 ( echo Copy failed. & exit /b 1 )

echo.
echo === Writing %DST%\.env.local ===
(
  echo # Auto-generated by clone-company.bat
  echo COMPANY_NAME=%NAME%
  echo POSTGRES_DB=%NAME%_db
  echo POSTGRES_USER=%NAME%_user
  echo POSTGRES_PASSWORD=change_me_now
  echo WEB_PORT=%WEBPORT%
  echo API_PORT=%APIPORT%
  echo DB_PORT=%DBPORT%
) > "%DST%\.env.local"

echo.
echo === Writing %DST%\docker-compose.override.yml ===
(
  echo services:
  echo   db:
  echo     container_name: %NAME%_db
  echo     ports:
  echo       - "%DBPORT%:5432"
  echo     volumes:
  echo       - %NAME%_pgdata:/var/lib/postgresql/data
  echo   api:
  echo     container_name: %NAME%_api
  echo     ports:
  echo       - "%APIPORT%:4000"
  echo   web:
  echo     container_name: %NAME%_web
  echo     ports:
  echo       - "%WEBPORT%:80"
  echo volumes:
  echo   %NAME%_pgdata:
) > "%DST%\docker-compose.override.yml"

echo.
echo ============================================================
echo  Clone complete.
echo.
echo  Next steps:
echo    1. cd /d "%DST%"
echo    2. Edit .env.local and set POSTGRES_PASSWORD
echo    3. docker compose --env-file .env.local up -d --build
echo    4. Open http://localhost:%WEBPORT%
echo    5. Sign in, then go to Settings to set the company name
echo       (currently shows as "Landco Lda" until you change it).
echo ============================================================

endlocal
