#!/usr/bin/env bash
# ============================================================
#  Fix sync: load SUPABASE_SERVICE_ROLE_KEY into API container
# ============================================================
set -e
cd "$(dirname "$0")/.."

echo
echo "============================================================"
echo "  LANACC - Fix Cloud Sync (paste service-role key)"
echo "============================================================"
echo
echo "Find the key in: Lovable -> Cloud -> Backend -> API keys -> service_role"
echo
read -r -p "Paste SUPABASE_SERVICE_ROLE_KEY: " SRK

if [ -z "$SRK" ]; then
  echo "[ERROR] No key entered. Aborting."
  exit 1
fi

cat > .env.local <<EOF
# Auto-generated by fix_sync.sh - DO NOT COMMIT
SUPABASE_SERVICE_ROLE_KEY=${SRK}
EOF
echo "Wrote .env.local"

echo
echo "--- Rebuilding + recreating API container (picks up latest sync.js AND the new key) ---"
docker compose --env-file .env.local up -d --build --force-recreate api

echo
echo "--- Waiting for API to come up ---"
for i in $(seq 1 15); do
  if curl -sf http://localhost:4000/api/sync/status >/dev/null 2>&1; then break; fi
  sleep 1
done

echo
echo "--- /api/sync/status ---"
curl -s http://localhost:4000/api/sync/status
echo
echo
echo 'If "service_role_key_loaded": true, you are done.'
echo "Now run Sync -> Pull Cloud -> Local in the app."
