@echo off
REM ============================================================
REM  Fix sync: load SUPABASE_SERVICE_ROLE_KEY into API container
REM ============================================================
setlocal
cd /d "%~dp0\.."

echo.
echo ============================================================
echo   LANACC - Fix Cloud Sync (paste service-role key)
echo ============================================================
echo.
echo Find the key in: Lovable -^> Cloud -^> Backend -^> API keys -^> service_role
echo.
set /p SRK="Paste SUPABASE_SERVICE_ROLE_KEY: "

if "%SRK%"=="" (
  echo [ERROR] No key entered. Aborting.
  exit /b 1
)

> .env.local echo # Auto-generated by fix_sync.bat - DO NOT COMMIT
>> .env.local echo SUPABASE_SERVICE_ROLE_KEY=%SRK%
echo Wrote .env.local

echo.
echo --- Recreating API container so it picks up the new key ---
docker compose --env-file .env.local up -d --force-recreate api

echo.
echo --- Waiting for API to come up ---
timeout /t 5 /nobreak >nul

echo.
echo --- Checking /api/sync/status ---
curl -s http://localhost:4000/api/sync/status
echo.
echo.
echo If "service_role_key_loaded": true, you are done.
echo Now run Sync -^> Pull Cloud -^> Local in the app.
echo.
endlocal
