#!/usr/bin/env bash
# ============================================================
#  LANACC - One-shot setup for a NEW Mac / Linux machine
# ------------------------------------------------------------
#  Run this once, from the project root, after cloning and
#  installing Docker.
# ============================================================
set -e
cd "$(dirname "$0")/.."

echo
echo "============================================================"
echo "  LANACC - New Machine Setup"
echo "============================================================"
echo

# ---- Step 1: service-role key --------------------------------
echo "--- Step 1 of 4: Supabase service-role key ---"
echo
echo "The service-role key is REQUIRED to push local changes to the cloud."
echo "Find it in: Lovable -> Cloud -> Backend -> API keys -> service_role"
echo "Press Enter to skip (local-only mode)."
echo
read -r -p "SUPABASE_SERVICE_ROLE_KEY: " SRK

cat > .env.local <<EOF
# Auto-generated by setup_new_machine.sh - DO NOT COMMIT
# This file is gitignored (matches *.local).
SUPABASE_SERVICE_ROLE_KEY=${SRK}
EOF
echo "Wrote .env.local"

# ---- Step 2: docker compose up -------------------------------
echo
echo "--- Step 2 of 4: building and starting containers ---"
docker compose --env-file .env.local up -d --build

# ---- Step 3: wait for db -------------------------------------
echo
echo "--- Step 3 of 4: waiting for database to be ready ---"
for i in $(seq 1 30); do
  if docker exec lanacc-db pg_isready -U postgres -d landco_v2_db >/dev/null 2>&1; then
    echo "Database is ready."
    break
  fi
  sleep 2
done

# ---- Step 4: reset admin users -------------------------------
echo
echo "--- Step 4 of 4: creating / resetting admin users ---"
bash "$(dirname "$0")/reset_admin_users.sh" || \
  echo "[WARN] Admin reset failed. Re-run scripts/reset_admin_users.sh manually."

echo
echo "============================================================"
echo "  SETUP COMPLETE"
echo "============================================================"
echo "  Open the app:    http://localhost:8080"
echo "  Login as:        cwschnell@gmail.com / Abcd7654\$"
echo "                   andrisa.schnell@gmail.com / Abcd7654#"
echo "============================================================"
