@echo off
REM ============================================================
REM  LANACC - One-shot setup for a NEW Windows machine
REM ------------------------------------------------------------
REM  Run this once, from the project root, after cloning the
REM  repo and installing Docker Desktop.
REM
REM  It will:
REM    1. Ask for your Supabase SERVICE-ROLE key (needed for
REM       Local -> Cloud sync). You can press Enter to skip and
REM       run in local-only mode.
REM    2. Write that key to .env.local (auto-ignored by git).
REM    3. docker compose up -d --build
REM    4. Wait for the database, then run reset_admin_users.bat
REM       so you can log in immediately as the two admins.
REM ============================================================

setlocal ENABLEDELAYEDEXPANSION
cd /d "%~dp0\.."

echo.
echo ============================================================
echo  LANACC - New Machine Setup
echo ============================================================
echo.
echo This will configure THIS computer to run Landco Lodge Accounting.
echo You only need to run it once per machine.
echo.

REM ---- Step 1: Service-role key ---------------------------------
echo --- Step 1 of 4: Supabase service-role key ---
echo.
echo The service-role key is REQUIRED if you want to push local
echo changes to the cloud database. You can find it in:
echo    Lovable -^> Cloud -^> Backend -^> API keys -^> service_role
echo.
echo Paste it now, or just press Enter to skip (local-only mode).
echo.
set /p SRK="SUPABASE_SERVICE_ROLE_KEY: "

(
  echo # Auto-generated by setup_new_machine.bat - DO NOT COMMIT
  echo # This file is gitignored ^(matches *.local^).
  echo SUPABASE_SERVICE_ROLE_KEY=!SRK!
) > .env.local

echo Wrote .env.local
echo.

REM ---- Step 2: docker compose up --------------------------------
echo --- Step 2 of 4: building and starting containers ---
echo.
docker compose --env-file .env.local up -d --build
if errorlevel 1 (
  echo [ERROR] docker compose failed. Is Docker Desktop running?
  exit /b 1
)

REM ---- Step 3: wait for database --------------------------------
echo.
echo --- Step 3 of 4: waiting for database to be ready ---
set TRIES=0
:waitdb
set /a TRIES+=1
docker exec lanacc-db pg_isready -U postgres -d landco_v2_db >nul 2>&1
if not errorlevel 1 goto dbready
if %TRIES% GEQ 30 (
  echo [ERROR] Database did not become ready in 60 seconds.
  echo Check: docker logs lanacc-db
  exit /b 1
)
timeout /t 2 /nobreak >nul
goto waitdb
:dbready
echo Database is ready.

REM ---- Step 4: reset admin users --------------------------------
echo.
echo --- Step 4 of 4: creating / resetting admin users ---
call "%~dp0reset_admin_users.bat"
if errorlevel 1 (
  echo [WARN] Admin reset failed. You can re-run scripts\reset_admin_users.bat manually.
)

echo.
echo ============================================================
echo  SETUP COMPLETE
echo ============================================================
echo.
echo  Open the app:    http://localhost:8080
echo  Login as:        cwschnell@gmail.com / Abcd7654$
echo                   andrisa.schnell@gmail.com / Abcd7654#
echo.
echo  To switch this machine between Local and Cloud database,
echo  use the toggle on the login page or in the header.
echo.
echo  To re-run admin reset later:   scripts\reset_admin_users.bat
echo  To back up the local DB:       scripts\backup.bat
echo ============================================================
endlocal
